# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-09 06:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_menu_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='photo',
        ),
    ]
